"""empty message

Revision ID: 061425c6a76a
Revises: 997027f47a25
Create Date: 2022-01-08 17:18:14.436060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '061425c6a76a'
down_revision = '997027f47a25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary', schema=None) as batch_op:
        batch_op.alter_column('first_mu',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('second_mu',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary', schema=None) as batch_op:
        batch_op.alter_column('second_mu',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('first_mu',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
