"""empty message

Revision ID: 79466024c6d7
Revises: 5d70c8b4911f
Create Date: 2022-01-08 16:59:21.457884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79466024c6d7'
down_revision = '5d70c8b4911f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_mu', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('second_mu', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary', schema=None) as batch_op:
        batch_op.drop_column('second_mu')
        batch_op.drop_column('first_mu')

    # ### end Alembic commands ###
