"""empty message

Revision ID: ecf757cfa6a2
Revises: 79466024c6d7
Create Date: 2022-01-08 17:12:12.085789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecf757cfa6a2'
down_revision = '79466024c6d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary', schema=None) as batch_op:
        batch_op.alter_column('first_mu',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary', schema=None) as batch_op:
        batch_op.alter_column('first_mu',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
